#!/usr/bin/env python3
# prov: 2026-10-02 drafted (Claude Code)
# fable_review: pending
"""
contents_key_diff.py -- what the 2026-10-02 Contents-reader fix would move.

    python3 pipeline/contents_key_diff.py            # print the summary
    python3 pipeline/contents_key_diff.py --write    # also write docs/review/2026-10-02-contents-key-ids.md

The fix (structure_texts.py, RE_CONTENTS_NUM / RE_CONTENTS_TAIL) stops the
Contents reader cutting letters off titles ("The Mice in Council" was read as
"The Mice in Coun"). The reader builds each book's heading pattern, headings
decide which chapter a paragraph is filed under, and the unit id is
`<slug>:<chapter>.<paragraph>`. So for every committed book built from its own
Contents (convert_gutenberg_prose + contents_chapre: CHESTERTON_GUTENBERG),
this builds the book twice from the same text, old rule and new, and lists
every unit whose id differs, old -> new.

Paragraphs are matched by their text (and which occurrence of that text it
is), never by position, so a paragraph that became a heading shows as removed
and nothing else shifts with it. Reads data/corpus/<slug>.txt; a book whose
text is not fetched is listed as NOT MEASURED, never as unchanged. Writes
nothing but the report, and only with --write.
"""
import json
import os
import sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import fetch_sources as F       # noqa: E402
import structure_texts as S     # noqa: E402

REPORT = os.path.join(ROOT, "docs", "review", "2026-10-02-contents-key-ids.md")


def keyed(units):
    seen, out = defaultdict(int), {}
    for u in units:
        seen[u["text"]] += 1
        out[(u["text"], seen[u["text"]])] = u["id"]
    return out


def diff_book(path, slug, title, author):
    old = S.convert_gutenberg_prose(path, slug, title, author, S.contents_chapre(path, old=True))
    new = S.convert_gutenberg_prose(path, slug, title, author, S.contents_chapre(path))
    a, b = keyed(old["units"]), keyed(new["units"])
    rows = []
    for k, oid in a.items():
        nid = b.get(k)
        if nid != oid:
            rows.append((oid, nid or "(now a heading, no unit)"))
    rows += [("(was not a unit)", nid) for k, nid in b.items() if k not in a]
    return len(old["units"]), len(new["units"]), rows


def main():
    write = "--write" in sys.argv
    manifest = json.load(open(os.path.join(ROOT, "data", "books", "manifest.json"), encoding="utf-8"))
    results = []
    for slug, (_gid, title, author) in F.CHESTERTON_GUTENBERG.items():
        if slug not in manifest:
            continue
        path = os.path.join(S.CORPUS, slug + ".txt")
        if not os.path.exists(path):
            results.append((slug, None))
            continue
        sha_ok = S.sha256(path) == manifest[slug].get("sha256")
        results.append((slug, (sha_ok,) + diff_book(path, slug, title, author)))
    measured = [r for r in results if r[1]]
    moved = [r for r in measured if r[1][3]]
    print(f"{len(results)} committed books built from their own Contents; "
          f"{len(measured)} measured, {len(moved)} with ids that change, "
          f"{len(results) - len(measured)} NOT MEASURED (text not fetched)")
    for slug, r in results:
        if r is None:
            print(f"  {slug}: NOT MEASURED")
        else:
            print(f"  {slug}: {r[1]} -> {r[2]} units, {len(r[3])} ids change"
                  + ("" if r[0] else "  (text differs from the manifest sha256)"))
    if not write:
        return
    L = ["# Contents-reader fix: which unit ids move (2026-10-02)", "",
         "**Needs Adam's ruling (CLAUDE.md rule 3).** The fix is on PR #6 as its own",
         "commit; nothing has been rebuilt. Generated by `pipeline/contents_key_diff.py --write`.",
         "No uid in `data/uids/wordhoard.uids.json` points at any of these books, so a",
         "change moves citations into the gitignored built books and the manifest's",
         "unit counts only.", "",
         "| book | units before | after | ids that change | text matches manifest |",
         "|---|---|---|---|---|"]
    for slug, r in results:
        L.append(f"| {slug} | NOT MEASURED | | | text not fetched |" if r is None else
                 f"| {slug} | {r[1]} | {r[2]} | {len(r[3])} | {'yes' if r[0] else 'NO'} |")
    for slug, r in moved:
        L += ["", f"## {slug}", "", "| old id | new id |", "|---|---|"]
        L += [f"| `{o}` | `{n}` |" for o, n in r[3]]
    os.makedirs(os.path.dirname(REPORT), exist_ok=True)
    with open(REPORT + ".tmp", "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(L) + "\n")
    os.replace(REPORT + ".tmp", REPORT)
    print(f"wrote {os.path.relpath(REPORT, ROOT)}")


if __name__ == "__main__":
    main()
