#!/usr/bin/env python3
"""Census of the English translations Perseus serves, against what canon-corpus holds.

    python3 pipeline/perseus_census.py [scaife.json]
Reads the Scaife Viewer library catalogue (https://scaife.perseus.org/library/json/,
fetched if no path is given), keeps every text with lang "eng" in greekLit and
latinLit, and writes docs/perseus-census.csv plus docs/perseus-census.md.
Measures only; fetches no text. Status per row:
  in-build      the exact edition is in fetch_sources.PERSEUS
  author-shelf  the author has a pipeline/<name>_shelf.json (another edition held)
  gap           neither
likely_pd is a HEURISTIC from the latest year in the edition's bibliographic
description (<= 1930: US public domain likely). Read the rights line of the
exact edition before acquiring anything (CLAUDE.md, rights gate).
"""
import csv, glob, json, os, re, sys, urllib.request
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
sys.path.insert(0, HERE)

# Same translation already held under another slug (checked by hand, 2026-10-02).
HELD = {
    "tlg0013.": "hesiod-evelyn-white (Evelyn-White 1914 Homeric Hymns, in the Hesiod volume)",
    "tlg0012.tlg003.perseus-eng1": "hesiod-evelyn-white (Evelyn-White 1914 Epigrams of Homer)",
}

def load(path):
    if path:
        return json.load(open(path, encoding="utf-8"))
    req = urllib.request.Request("https://scaife.perseus.org/library/json/",
                                 headers={"User-Agent": "Canon-Corpus/0.1"})
    return json.load(urllib.request.urlopen(req, timeout=180))

def main():
    d = load(sys.argv[1] if len(sys.argv) > 1 else None)
    from fetch_sources import PERSEUS
    in_build = {p.rsplit("/", 1)[-1][:-4]: slug for slug, (_, p, _) in PERSEUS.items()}
    shelves = {os.path.basename(f)[:-11] for f in glob.glob(os.path.join(HERE, "*_shelf.json"))}
    groups = {g["urn"]: (g.get("label") or "").strip() for g in d["text_groups"]}
    works = {w["urn"]: (w.get("label") or "").strip() for w in d["works"]}
    rows = []
    for t in d["texts"]:
        urn = t["urn"]; ns = urn.split(":")[2]
        if t.get("lang") != "eng" or ns not in ("greekLit", "latinLit"):
            continue
        work = urn.rsplit(".", 1)[0]; group = work.rsplit(".", 1)[0]
        author = groups.get(group, "")
        desc = re.sub(r"\s+", " ", t.get("description") or "").strip()
        years = [int(y) for y in re.findall(r"\b(1[5-9]\d\d|20[0-2]\d)\b", desc)]
        year = max(years) if years else None
        cts_id = urn.split(":")[-1]
        a = author.lower()
        shelf = next((s for s in sorted(shelves) if s in a), None)
        held = next((v for k, v in HELD.items() if cts_id.startswith(k)), None)
        status = ("in-build:" + in_build[cts_id]) if cts_id in in_build else \
                 ("held:" + held) if held else \
                 ("author-shelf:" + shelf) if shelf else "gap"
        pd = ("yes" if year and year <= 1930 else "check" if year else "unknown")
        if "World English Bible" in desc:
            pd = "yes (WEB: public-domain dedication)"
        rows.append({"urn": urn, "author": author, "work": works.get(work, ""),
                     "label": re.sub(r"\s+", " ", t.get("label") or "").strip(),
                     "year": year or "", "likely_pd": pd,
                     "status": status, "description": desc[:300]})
    rows.sort(key=lambda r: (r["author"], r["work"], r["urn"]))
    out = os.path.join(ROOT, "docs")
    with open(os.path.join(out, "perseus-census.csv"), "w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0])); w.writeheader(); w.writerows(rows)
    by = defaultdict(list)
    for r in rows:
        by[r["author"]].append(r)
    n_gap = sum(r["status"] == "gap" for r in rows)
    n_gap_pd = sum(r["status"] == "gap" and r["likely_pd"].startswith("yes") for r in rows)
    L = ["# Perseus English translations: census against canon-corpus", "",
         "GENERATED by `pipeline/perseus_census.py` from the Scaife Viewer library catalogue. "
         "Measures only; nothing fetched. Full rows: `docs/perseus-census.csv`.", "",
         f"- English texts in greekLit + latinLit: **{len(rows)}** across **{len(by)}** authors",
         f"- in the build manifest (`fetch_sources.PERSEUS`): **{sum(r['status'].startswith('in-build') for r in rows)}**",
         f"- author already has a shelf (another edition held): **{sum(r['status'].startswith('author-shelf') for r in rows)}**",
         f"- same translation already held under another slug: **{sum(r['status'].startswith('held') for r in rows)}**",
         f"- gap: **{n_gap}**, of which **{n_gap_pd}** look US public domain by the year in their description (heuristic; read the rights line before acquiring)",
         "", "Fetching any of these needs a `PERSEUS` entry in `fetch_sources.py` (or a Perseus mode for "
         "`fetch_shelf.py`); neither was done during the relay burst. Sophocles (Jebb, 7 plays) is in "
         "the unmerged Thayer/Sophocles PR and shows as a gap here until it lands. The Old and New "
         "Testament rows are the World English Bible, public domain by dedication; the year heuristic "
         "misreads it, so it is overridden. The year heuristic is only a sorting aid.", "",
         "| Author | English texts | gap | gap, likely PD | status |", "|---|---|---|---|---|"]
    for a in sorted(by, key=lambda a: (-sum(r["status"] == "gap" for r in by[a]), a)):
        rs = by[a]
        st = sorted({r["status"].split(":")[0] for r in rs})
        L.append(f"| {a or '(unnamed)'} | {len(rs)} | {sum(r['status']=='gap' for r in rs)} | "
                 f"{sum(r['status']=='gap' and r['likely_pd'].startswith('yes') for r in rs)} | {', '.join(st)} |")
    open(os.path.join(out, "perseus-census.md"), "w", encoding="utf-8").write("\n".join(L) + "\n")
    print(len(rows), "rows;", n_gap, "gap;", n_gap_pd, "gap likely PD")

if __name__ == "__main__":
    main()
