#!/usr/bin/env python3
"""Check the omnibus plan against the canon-corpus collection.

Reads plan/omnibus.csv, the committed canon-corpus manifest
(data/books/manifest.json) and its Great Books shelf
(pipeline/adler_shelf.json), and writes plan/GAPS.md: for every chapter,
whether its text is already built, already on the shelf (fetchable by
ingest_adler.py), still to acquire, or not public domain.

A `corpus` value that names nothing in either file is an error: the plan
must never claim a text the corpus does not have.

    python3 tools/gap_check.py                       # corpus at ../canon-corpus
    python3 tools/gap_check.py --corpus /path/to/canon-corpus
"""
import argparse
import csv
import json
import sys
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
VOLUMES = {
    "1": "I. The Ancient World (primary)",
    "2": "II. Fathers to the Reformation (primary)",
    "3": "III. The Modern World (primary)",
    "4": "IV. The Ancient World (secondary)",
    "5": "V. Fathers to the Reformation (secondary)",
    "6": "VI. The Modern World (secondary)",
}
LABEL = {
    "built": "✅ built",
    "shelf": "📚 on shelf",
    "acquire": "⬜ to acquire",
    "not-pd": "⛔ not PD",
    "missing": "❌ bad slug",
}


def status(row, manifest, shelf):
    if row["rights"] == "not-pd":
        return "not-pd"
    slug = row["corpus"].strip()
    if not slug:
        return "acquire"
    if slug in manifest:
        return "built"
    if slug in shelf:
        return "shelf"
    return "missing"


def us_pd_year(year):
    # US: works published 1930 or earlier are PD as of 2026; publication
    # year + 95 years, entering on 1 January of the following year.
    return int(year) + 96 if year else None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--corpus", default=str(HERE.parent / "canon-corpus"))
    args = ap.parse_args()
    corpus = Path(args.corpus)
    manifest = json.loads((corpus / "data/books/manifest.json").read_text())
    shelf = json.loads((corpus / "pipeline/adler_shelf.json").read_text())

    rows = list(csv.DictReader(open(HERE / "plan/omnibus.csv", newline="")))
    out = ["# Omnibus — corpus gap report", "",
           "Generated by `tools/gap_check.py`. Do not hand-edit; edit "
           "`plan/omnibus.csv` and rerun.", ""]
    totals, errors = Counter(), []
    for vol, title in VOLUMES.items():
        chapters = [r for r in rows if r["vol"] == vol]
        out += [f"## {title}", "", "| # | Work | Author | Edition | Status | Notes |",
                "|---|---|---|---|---|---|"]
        for r in chapters:
            s = status(r, manifest, shelf)
            totals[s] += 1
            note = r["notes"]
            if s == "missing":
                errors.append(f"vol {vol} ch {r['ch']}: corpus slug "
                              f"{r['corpus']!r} is in neither manifest nor shelf")
            if s == "acquire" and r["source"]:
                note = f"{r['source']}. {note}".strip(". ")
            if s == "not-pd":
                note = f"US PD 1 Jan {us_pd_year(r['year'])}. {note}".strip(". ")
            if r["rights"] == "pd-us":
                note = f"PD in the US only. {note}".strip(". ")
            ed = r["edition"] + (f" ({r['year']})" if r["year"] else "")
            out.append(f"| {r['ch']} | {r['work']} | {r['author']} | {ed} | "
                       f"{LABEL[s]} | {note} |")
        out.append("")
    summary = ", ".join(f"{LABEL[k]}: {totals[k]}" for k in LABEL if totals[k])
    out[4:4] = [f"**{len(rows)} chapters.** {summary}", ""]
    (HERE / "plan/GAPS.md").write_text("\n".join(out))
    print(f"{len(rows)} chapters — {summary}")
    for e in errors:
        print("ERROR", e, file=sys.stderr)
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
